services:
  bot:
    image: bakteriachan/extra-dimensional:master
    environment:
      - TOKEN=${TOKEN}
      - revisionchat=${revisionchat}
      - mainchannel=${mainchannel}
    volumes:
      - persistence:/persistence
volumes:
  persistence:
